spring:
  application:
    name: server

debug: true  # 운영에서는 false 권장

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

cors:
  allowed-origins:
    - http://localhost:5173
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Content-Type
  max-age: 3600
  allow-credentials: true

env:
  SPRING_PROFILES_ACTIVE: test