spring:
  profiles:
    include: dbconn
  application:
    name: server
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      platform: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: public
    schemas: public
    baseline-on-migrate: true
    baseline-version: 1
    clean-disabled: true

debug: true  # 운영에서는 false 권장

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

cors:
  allowed-origins:
    - http://localhost:5173
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - Authorization
    - Content-Type
  max-age: 3600
  allow-credentials: true

env:
  SPRING_PROFILES_ACTIVE: test

logging:
  level:
    org.springframework.boot.autoconfigure: ERROR