spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  application:
    name: green-cloud
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
  sql:
    init:
      platform: postgres
  flyway:
    enabled: true
    locations: classpath:db/migration
    default-schema: public
    schemas: public
    baseline-on-migrate: true
    baseline-version: 1
    clean-disabled: true

debug: true  # 운영에서는 false 권장

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

env:
  SPRING_PROFILES_ACTIVE: test

# 로그 설정
logging:
  level:
    org.springframework.security: INFO

jwt:
  access-token-exp-seconds: 900        # 15분
  refresh-token-exp-seconds: 1209600   # 14일