name: CI

on:
  push:
    branches: [ main, develop, develop-server ]
  pull_request:
    branches: [ main, develop, develop-server ]

jobs:
  server:
    runs-on: ubuntu-latest
    name: Server (Spring Boot)

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping || exit 1"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 10

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Server tests
        working-directory: server
        run: ./gradlew --no-daemon build
        env:
          # 프로필: 테스트로 고정
          SPRING_PROFILES_ACTIVE: test

          # DB (서비스 postgresql과 매칭)
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/testdb
          SPRING_DATASOURCE_USERNAME: user
          SPRING_DATASOURCE_PASSWORD: password

          # Redis (서비스 redis와 매칭)
          SPRING_REDIS_HOST: localhost
          SPRING_REDIS_PORT: 6379

          # JWT (Secrets에 저장 권장)
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_ACCESS_TOKEN_EXP_SECONDS: 900
          JWT_REFRESH_TOKEN_EXP_SECONDS: 1209600

          # Flyway를 테스트에서 끄고 싶다면 false (DB 마이그레이션이 테스트에 꼭 필요 없다면 권장)
          FLYWAY_ENABLED: false